/**
 * ChargebackForm is a shared form used by the Add and Edit dialogs.
 *
 * It collects amount, currency, and reason. The ID is either generated by the
 * caller (Add) or comes from the existing record (Edit).
 */
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import type { ChargebackInput } from '@/types/chargeback'

interface ChargebackFormProps {
  initial?: ChargebackInput
  onSubmit: (data: ChargebackInput) => void
  onCancel: () => void
  isPending: boolean
  submitLabel: string
}

export function ChargebackForm({
  initial,
  onSubmit,
  onCancel,
  isPending,
  submitLabel,
}: ChargebackFormProps) {
  const [amount, setAmount] = useState(initial?.amount?.toString() ?? '')
  const [currency, setCurrency] = useState(initial?.currency ?? 'USD')
  const [reason, setReason] = useState(initial?.reason ?? '')

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    onSubmit({
      amount: Math.round(parseFloat(amount) * 100), // convert dollars → cents
      currency: currency.toUpperCase(),
      reason,
    })
  }

  return (
    <form onSubmit={handleSubmit} className="grid gap-4">
      <div className="grid gap-1.5">
        <Label htmlFor="amount">Amount (in dollars)</Label>
        <Input
          id="amount"
          type="number"
          min="0.01"
          step="0.01"
          placeholder="10.00"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          required
        />
      </div>

      <div className="grid gap-1.5">
        <Label htmlFor="currency">Currency (ISO 4217)</Label>
        <Input
          id="currency"
          type="text"
          maxLength={3}
          placeholder="USD"
          value={currency}
          onChange={(e) => setCurrency(e.target.value)}
          required
        />
      </div>

      <div className="grid gap-1.5">
        <Label htmlFor="reason">Reason</Label>
        <Input
          id="reason"
          type="text"
          placeholder="Duplicate charge"
          value={reason}
          onChange={(e) => setReason(e.target.value)}
          required
        />
      </div>

      <div className="flex justify-end gap-2 pt-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={isPending}>
          Cancel
        </Button>
        <Button type="submit" disabled={isPending}>
          {isPending ? 'Saving…' : submitLabel}
        </Button>
      </div>
    </form>
  )
}
